# -*- coding: utf-8 -*-
"""Final Exam

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4nsngOcT7kX-wv__nMFOV3o4079BC77

# **Q1**
"""

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string)-1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string)-1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string) - 1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string)-1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string)-1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string)-1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

string = input("Enter a string: ")
if string.isupper() :
  print("Contains only uppercase letters")
elif string[0].isupper() :
  print("Starts with an uppercase letter.")
elif string[len(string)-1] == "," :
  print("Ends with a comma")  
elif string.isalpha() :
  print("Contains only letters.")
elif  string.isdigit() :
  print("Contains only digits.")
elif string.isalnum() :
  print("Contains only letters and digits.")
elif not (string.isalnum () ) :
  print("No condition was met.")

"""# **Q2**"""

values = []
count = 0
number = int(input("Enter a number (0 to stop): "))
values.append(number)
while number :
   if number != 0 :
     number = int(input("Enter a number (0 to stop): "))
     values.append(number)
     count = count +1 
  

Average = round (sum(values) / count , 1 )
Smallest = min(values)
Largest = max(values)
Range = (Largest - Smallest ) 
print("Average : " ,Average )
print("Smallest :" , Smallest)
print("Largest :" , Largest)
print("Range between smallest and largest: " , float(Range) )

"""# **Q3**"""

def main() :
   string = input("Enter a string: ")
   n = int(input("How many times to repeat the string: "))
   delim = input("Delimiter: ")
   repeat(string , n , delim)
def repeat(string, n, delim) :
   result = (string + delim ) * n 
   print(result)
main()

"""# **Q4**"""

from random import randint
def main() :
  res = make_list()
  print("The content of the list:" , res )
  even_index(res)
  even_element(res)
  elements_reverse(res)
  first_last(res)
      
def make_list() :
    values = []
    for i in range(10):
        i = randint(-99 , 99)
        values.append(int(i))
    return values
def even_index(list) :
  print("Elements at an even index")
  for i in range(len(list))  :
    if (i % 2) == 0 :
      print(list[i])
def even_element(list) :
  print("Every even element")
  for x in list :
    if (x%2) == 0 :
      print(x)
def elements_reverse(list) :
  print("All elements in reversed order")
  for i in range(9) :
     list[i] = list[9- i]
  for i in list :
    print(i)
    
def first_last(list) :
  print("Only the first and last element ")
  print(list[0] , list[-1])
      
   

main()